package com.tripmanagementsystem.tripmanagementsystem.model;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

@Entity
@Data
@Table(name = "bookings")
public class Booking {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user; // The user who made the booking

    @ManyToOne
    @JoinColumn(name = "product_id", nullable = false)
    private Product product; // The product being booked

    private LocalDateTime bookingDate; // Date and time of the booking
    private String status; // e.g., "confirmed", "canceled"

    // Getters and setters are generated by Lombok
}