package com.tripmanagementsystem.tripmanagementsystem.model;

import jakarta.persistence.*;
import lombok.Data;

@Entity
@Data
@Table(name = "products")
public class Product {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private String category;
    private double price; // Use double or BigDecimal for currency
    private String description;

    private String imageUrl; // URL for product image

    // Getters and setters are generated by Lombok
}