package com.tripmanagementsystem.tripmanagementsystem.model;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

@Entity
@Data
@Table(name = "reviews")
public class Review {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user; // The user who wrote the review

    @ManyToOne
    @JoinColumn(name = "product_id", nullable = false)
    private Product product; // The product being reviewed

    private int rating; // Rating out of 5
    private String comment; // Review comment
    private LocalDateTime reviewDate; // Date of the review

    // Getters and setters are generated by Lombok
}